### ISSUE TITLE
Bug - Glitch when row is completed

### ISSUE THREAD

**Issue by neilswann80** [neilswann80/pbtetris#1]
@orontee reported:

"I think there's a small annoying bug: After a row is removed, the last raw of the new block (at the top of the playground) is duplicated during one or two seconds..."

**Comment by neilswann80** [comment]
What device and resolution are you testing from?  From the screenshot of Taranis on your Github page it looks like you have the Vivilio branded PB632.  I have the Pocketbook branded PB632, I believe it's identical hardware.  I can't replicate the issue on my device though.  Does it happen with every cleared row?  With multiple  cleared rows also?  Could you pause the game as it happens and grab a screenshot please?

I think the issue is related to an issue I've been working around with the system statusbar (main pocketbook statusbar).  Although the app seems to be full screened,  if I place any content in the area the statusbar would appear it isn't visible.  If you have any suggestions please let me know.  

I've tried calling the function `iv_fullscreen();` but no change.

EDIT - Sorted the statusbar issue.  Needed to add:
`SetPanelType(0);`
to the initial draw.

I'll try recompiling...

**Comment by neilswann80** [comment]
@orontee

Could you try the latest release again now please?

**Comment by orontee** [comment]
Not at home at present time, I'll check this evening.

**Comment by orontee** [comment]
@neilswann80 I confirm the problem is gone. Good job!

**Comment by neilswann80** [comment]
Hopefully the glitch is now resolved.
