### ISSUE TITLE
Strange file path for highscores

### ISSUE THREAD

**Issue by orontee** [neilswann80/pbtetris#2]
The `pbtetris-highscore.dat` file is currently saved at the root of the external file system. I noticed that file while browsing my PocketBook; I am expecting such files to be under `/system`.

**Comment by neilswann80** [comment]
Thanks, good idea!

**Comment by neilswann80** [comment]
Now saves to: `/system/state/pbtetris-highscore.dat`

Move the dat file to `/system/state` if you wish to keep the score from the old version.
